name: Cartas espa√±olas de truco
rules:
  - { image: FlechaIzquierda.png, when: { black:   0, blue:   0, green: 0, red: 100 } } 
  - { image: FlechaDerecha.png,   when: { black:   0, blue:   0, green: 0, red: 200 } } 
  - { image: Reverso.png,    when: { black: '*', blue: '*', green: 0, red: 1 } } 
  - { image: Espadas-01.png, when: { black:   1, blue:   1, green: 0, red:  0 } } 
  - { image: Espadas-02.png, when: { black:   1, blue:   2, green: 0, red:  0 } } 
  - { image: Espadas-03.png, when: { black:   1, blue:   3, green: 0, red:  0 } } 
  - { image: Espadas-04.png, when: { black:   1, blue:   4, green: 0, red:  0 } } 
  - { image: Espadas-05.png, when: { black:   1, blue:   5, green: 0, red:  0 } } 
  - { image: Espadas-06.png, when: { black:   1, blue:   6, green: 0, red:  0 } } 
  - { image: Espadas-07.png, when: { black:   1, blue:   7, green: 0, red:  0 } } 
  - { image: Espadas-10.png, when: { black:   1, blue:  10, green: 0, red:  0 } } 
  - { image: Espadas-11.png, when: { black:   1, blue:  11, green: 0, red:  0 } } 
  - { image: Espadas-12.png, when: { black:   1, blue:  12, green: 0, red:  0 } } 
  - { image: Oros-01.png,    when: { black:   2, blue:   1, green: 0, red:  0 } } 
  - { image: Oros-02.png,    when: { black:   2, blue:   2, green: 0, red:  0 } } 
  - { image: Oros-03.png,    when: { black:   2, blue:   3, green: 0, red:  0 } } 
  - { image: Oros-04.png,    when: { black:   2, blue:   4, green: 0, red:  0 } } 
  - { image: Oros-05.png,    when: { black:   2, blue:   5, green: 0, red:  0 } } 
  - { image: Oros-06.png,    when: { black:   2, blue:   6, green: 0, red:  0 } } 
  - { image: Oros-07.png,    when: { black:   2, blue:   7, green: 0, red:  0 } } 
  - { image: Oros-10.png,    when: { black:   2, blue:  10, green: 0, red:  0 } } 
  - { image: Oros-11.png,    when: { black:   2, blue:  11, green: 0, red:  0 } } 
  - { image: Oros-12.png,    when: { black:   2, blue:  12, green: 0, red:  0 } } 
  - { image: Bastos-01.png,  when: { black:   3, blue:   1, green: 0, red:  0 } } 
  - { image: Bastos-02.png,  when: { black:   3, blue:   2, green: 0, red:  0 } } 
  - { image: Bastos-03.png,  when: { black:   3, blue:   3, green: 0, red:  0 } } 
  - { image: Bastos-04.png,  when: { black:   3, blue:   4, green: 0, red:  0 } } 
  - { image: Bastos-05.png,  when: { black:   3, blue:   5, green: 0, red:  0 } } 
  - { image: Bastos-06.png,  when: { black:   3, blue:   6, green: 0, red:  0 } } 
  - { image: Bastos-07.png,  when: { black:   3, blue:   7, green: 0, red:  0 } } 
  - { image: Bastos-10.png,  when: { black:   3, blue:  10, green: 0, red:  0 } } 
  - { image: Bastos-11.png,  when: { black:   3, blue:  11, green: 0, red:  0 } } 
  - { image: Bastos-12.png,  when: { black:   3, blue:  12, green: 0, red:  0 } } 
  - { image: Copas-01.png,   when: { black:   4, blue:   1, green: 0, red:  0 } } 
  - { image: Copas-02.png,   when: { black:   4, blue:   2, green: 0, red:  0 } } 
  - { image: Copas-03.png,   when: { black:   4, blue:   3, green: 0, red:  0 } } 
  - { image: Copas-04.png,   when: { black:   4, blue:   4, green: 0, red:  0 } } 
  - { image: Copas-05.png,   when: { black:   4, blue:   5, green: 0, red:  0 } } 
  - { image: Copas-06.png,   when: { black:   4, blue:   6, green: 0, red:  0 } } 
  - { image: Copas-07.png,   when: { black:   4, blue:   7, green: 0, red:  0 } } 
  - { image: Copas-10.png,   when: { black:   4, blue:  10, green: 0, red:  0 } } 
  - { image: Copas-11.png,   when: { black:   4, blue:  11, green: 0, red:  0 } } 
  - { image: Copas-12.png,   when: { black:   4, blue:  12, green: 0, red:  0 } } 
  - { image: Iluminada-Espadas-01.png,  when: { black:   1, blue:   1, green: 1, red: 0 } } 
  - { image: Iluminada-Espadas-02.png,  when: { black:   1, blue:   2, green: 1, red: 0 } } 
  - { image: Iluminada-Espadas-03.png,  when: { black:   1, blue:   3, green: 1, red: 0 } } 
  - { image: Iluminada-Espadas-04.png,  when: { black:   1, blue:   4, green: 1, red: 0 } } 
  - { image: Iluminada-Espadas-05.png,  when: { black:   1, blue:   5, green: 1, red: 0 } } 
  - { image: Iluminada-Espadas-06.png,  when: { black:   1, blue:   6, green: 1, red: 0 } } 
  - { image: Iluminada-Espadas-07.png,  when: { black:   1, blue:   7, green: 1, red: 0 } } 
  - { image: Iluminada-Espadas-10.png,  when: { black:   1, blue:  10, green: 1, red: 0 } } 
  - { image: Iluminada-Espadas-11.png,  when: { black:   1, blue:  11, green: 1, red: 0 } } 
  - { image: Iluminada-Espadas-12.png,  when: { black:   1, blue:  12, green: 1, red: 0 } } 
  - { image: Iluminada-Oros-01.png,     when: { black:   2, blue:   1, green: 1, red: 0 } } 
  - { image: Iluminada-Oros-02.png,     when: { black:   2, blue:   2, green: 1, red: 0 } } 
  - { image: Iluminada-Oros-03.png,     when: { black:   2, blue:   3, green: 1, red: 0 } } 
  - { image: Iluminada-Oros-04.png,     when: { black:   2, blue:   4, green: 1, red: 0 } } 
  - { image: Iluminada-Oros-05.png,     when: { black:   2, blue:   5, green: 1, red: 0 } } 
  - { image: Iluminada-Oros-06.png,     when: { black:   2, blue:   6, green: 1, red: 0 } } 
  - { image: Iluminada-Oros-07.png,     when: { black:   2, blue:   7, green: 1, red: 0 } } 
  - { image: Iluminada-Oros-10.png,     when: { black:   2, blue:  10, green: 1, red: 0 } } 
  - { image: Iluminada-Oros-11.png,     when: { black:   2, blue:  11, green: 1, red: 0 } } 
  - { image: Iluminada-Oros-12.png,     when: { black:   2, blue:  12, green: 1, red: 0 } } 
  - { image: Iluminada-Bastos-01.png,   when: { black:   3, blue:   1, green: 1, red: 0 } } 
  - { image: Iluminada-Bastos-02.png,   when: { black:   3, blue:   2, green: 1, red: 0 } } 
  - { image: Iluminada-Bastos-03.png,   when: { black:   3, blue:   3, green: 1, red: 0 } } 
  - { image: Iluminada-Bastos-04.png,   when: { black:   3, blue:   4, green: 1, red: 0 } } 
  - { image: Iluminada-Bastos-05.png,   when: { black:   3, blue:   5, green: 1, red: 0 } } 
  - { image: Iluminada-Bastos-06.png,   when: { black:   3, blue:   6, green: 1, red: 0 } } 
  - { image: Iluminada-Bastos-07.png,   when: { black:   3, blue:   7, green: 1, red: 0 } } 
  - { image: Iluminada-Bastos-10.png,   when: { black:   3, blue:  10, green: 1, red: 0 } } 
  - { image: Iluminada-Bastos-11.png,   when: { black:   3, blue:  11, green: 1, red: 0 } } 
  - { image: Iluminada-Bastos-12.png,   when: { black:   3, blue:  12, green: 1, red: 0 } } 
  - { image: Iluminada-Copas-01.png,    when: { black:   4, blue:   1, green: 1, red: 0 } } 
  - { image: Iluminada-Copas-02.png,    when: { black:   4, blue:   2, green: 1, red: 0 } } 
  - { image: Iluminada-Copas-03.png,    when: { black:   4, blue:   3, green: 1, red: 0 } } 
  - { image: Iluminada-Copas-04.png,    when: { black:   4, blue:   4, green: 1, red: 0 } } 
  - { image: Iluminada-Copas-05.png,    when: { black:   4, blue:   5, green: 1, red: 0 } } 
  - { image: Iluminada-Copas-06.png,    when: { black:   4, blue:   6, green: 1, red: 0 } } 
  - { image: Iluminada-Copas-07.png,    when: { black:   4, blue:   7, green: 1, red: 0 } } 
  - { image: Iluminada-Copas-10.png,    when: { black:   4, blue:  10, green: 1, red: 0 } } 
  - { image: Iluminada-Copas-11.png,    when: { black:   4, blue:  11, green: 1, red: 0 } } 
  - { image: Iluminada-Copas-12.png,    when: { black:   4, blue:  12, green: 1, red: 0 } } 
