name: La cena de Dino
rules:
  - { image: Fondo.png              , when: { black:  1, blue:   0, green:   0, red:   0 } }
  - { image: Fondo.png              , when: { black:  2, blue:   0, green:   0, red:   0 } }
  - { image: Vacio.png              , when: { black:  0, blue:   0, green:   0, red:   0 } }
  - { image: Largada.png            , when: { black:  3, blue:   0, green:   0, red:   0 } }
  - { image: Banana-01.png          , when: { black:  1, blue:   0, green:   1, red:   0 } }
  - { image: Banana-02.png          , when: { black:  1, blue:   0, green:   2, red:   0 } }
  - { image: Banana-03.png          , when: { black:  1, blue:   0, green:   3, red:   0 } }
  - { image: Banana-04.png          , when: { black:  1, blue:   0, green:   4, red:   0 } }
  - { image: Banana-05.png          , when: { black:  1, blue:   0, green:   5, red:   0 } }
  - { image: Banana-06.png          , when: { black:  1, blue:   0, green:   6, red:   0 } }
  - { image: Banana-07.png          , when: { black:  1, blue:   0, green:   7, red:   0 } }
  - { image: Banana-08.png          , when: { black:  1, blue:   0, green:   8, red:   0 } }
  - { image: Banana-09.png          , when: { black:  1, blue:   0, green:   9, red:   0 } }
  - { image: Banana-10.png          , when: { black:  1, blue:   0, green:  10, red:   0 } }
  - { image: Banana-11.png          , when: { black:  1, blue:   0, green:  11, red:   0 } }
  - { image: Banana-12.png          , when: { black:  1, blue:   0, green:  12, red:   0 } }
  - { image: Banana-13.png          , when: { black:  1, blue:   0, green:  13, red:   0 } }
  - { image: Banana-14.png          , when: { black:  1, blue:   0, green:  14, red:   0 } }
  - { image: Banana-15.png          , when: { black:  1, blue:   0, green:  15, red:   0 } }
  - { image: Banana-16.png          , when: { black:  1, blue:   0, green:  16, red:   0 } }
  - { image: Banana-17.png          , when: { black:  1, blue:   0, green:  17, red:   0 } }
  - { image: Banana-18.png          , when: { black:  1, blue:   0, green:  18, red:   0 } }
  - { image: Banana-19.png          , when: { black:  1, blue:   0, green:  19, red:   0 } }
  - { image: BananaContada-01.png   , when: { black:  2, blue:   0, green:   1, red:   0 } }
  - { image: BananaContada-02.png   , when: { black:  2, blue:   0, green:   2, red:   0 } }
  - { image: BananaContada-03.png   , when: { black:  2, blue:   0, green:   3, red:   0 } }
  - { image: BananaContada-04.png   , when: { black:  2, blue:   0, green:   4, red:   0 } }
  - { image: BananaContada-05.png   , when: { black:  2, blue:   0, green:   5, red:   0 } }
  - { image: BananaContada-06.png   , when: { black:  2, blue:   0, green:   6, red:   0 } }
  - { image: BananaContada-07.png   , when: { black:  2, blue:   0, green:   7, red:   0 } }
  - { image: BananaContada-08.png   , when: { black:  2, blue:   0, green:   8, red:   0 } }
  - { image: BananaContada-09.png   , when: { black:  2, blue:   0, green:   9, red:   0 } }
  - { image: BananaContada-10.png   , when: { black:  2, blue:   0, green:  10, red:   0 } }
  - { image: BananaContada-11.png   , when: { black:  2, blue:   0, green:  11, red:   0 } }
  - { image: BananaContada-12.png   , when: { black:  2, blue:   0, green:  12, red:   0 } }
  - { image: BananaContada-13.png   , when: { black:  2, blue:   0, green:  13, red:   0 } }
  - { image: BananaContada-14.png   , when: { black:  2, blue:   0, green:  14, red:   0 } }
  - { image: BananaContada-15.png   , when: { black:  2, blue:   0, green:  15, red:   0 } }
  - { image: BananaContada-16.png   , when: { black:  2, blue:   0, green:  16, red:   0 } }
  - { image: BananaContada-17.png   , when: { black:  2, blue:   0, green:  17, red:   0 } }
  - { image: BananaContada-18.png   , when: { black:  2, blue:   0, green:  18, red:   0 } }
  - { image: BananaContada-19.png   , when: { black:  2, blue:   0, green:  19, red:   0 } }
  - { image: Manzana.png            , when: { black:  1, blue:   0, green:   0, red:   1 } }
  - { image: ManzanaContada.png     , when: { black:  2, blue:   0, green:   0, red:   2 } }
  - { image: MonoSolo.png           , when: { black:  1, blue:   1, green:   0, red:   0 } }
  - { image: MonoSolo.png           , when: { black:  2, blue:   1, green:   0, red:   0 } }
  - { image: MonoCaido.png          , when: { black:  0, blue:   1, green:   0, red:   0 } }
  - { image: MonoEnLargada.png      , when: { black:  3, blue:   1, green:   0, red:   0 } }
  - { image: MonoYBanana.png        , when: { black:  1, blue:   1, green: "+", red:   0 } }
  - { image: MonoYManzana.png       , when: { black:  1, blue:   1, green:   0, red: "+" } }
  - { image: MonoYBananaContada.png , when: { black:  2, blue:   1, green: "+", red:   0 } }
  - { image: MonoYManzanaContada.png, when: { black:  2, blue:   1, green:   0, red: "+" } }
  - { image: Espacio.png            , when: { black: 20, blue:   0, green:   0, red:   0 } }
  - { image: A.png                  , when: { black: 20, blue:   1, green:   0, red:   0 } }
  - { image: B.png                  , when: { black: 20, blue:   2, green:   0, red:   0 } }
  - { image: C.png                  , when: { black: 20, blue:   3, green:   0, red:   0 } }
  - { image: D.png                  , when: { black: 20, blue:   4, green:   0, red:   0 } }
  - { image: E.png                  , when: { black: 20, blue:   5, green:   0, red:   0 } }
  - { image: F.png                  , when: { black: 20, blue:   6, green:   0, red:   0 } }
  - { image: G.png                  , when: { black: 20, blue:   7, green:   0, red:   0 } }
  - { image: H.png                  , when: { black: 20, blue:   8, green:   0, red:   0 } }
  - { image: I.png                  , when: { black: 20, blue:   9, green:   0, red:   0 } }
  - { image: J.png                  , when: { black: 20, blue:  10, green:   0, red:   0 } }
  - { image: K.png                  , when: { black: 20, blue:  11, green:   0, red:   0 } }
  - { image: L.png                  , when: { black: 20, blue:  12, green:   0, red:   0 } }
  - { image: M.png                  , when: { black: 20, blue:  13, green:   0, red:   0 } }
  - { image: N.png                  , when: { black: 20, blue:  14, green:   0, red:   0 } }
  - { image: ENIE.png               , when: { black: 20, blue:  15, green:   0, red:   0 } }
  - { image: O.png                  , when: { black: 20, blue:  16, green:   0, red:   0 } }
  - { image: P.png                  , when: { black: 20, blue:  17, green:   0, red:   0 } }
  - { image: Q.png                  , when: { black: 20, blue:  18, green:   0, red:   0 } }
  - { image: R.png                  , when: { black: 20, blue:  19, green:   0, red:   0 } }
  - { image: S.png                  , when: { black: 20, blue:  20, green:   0, red:   0 } }
  - { image: T.png                  , when: { black: 20, blue:  21, green:   0, red:   0 } }
  - { image: U.png                  , when: { black: 20, blue:  22, green:   0, red:   0 } }
  - { image: V.png                  , when: { black: 20, blue:  23, green:   0, red:   0 } }
  - { image: W.png                  , when: { black: 20, blue:  24, green:   0, red:   0 } }
  - { image: X.png                  , when: { black: 20, blue:  25, green:   0, red:   0 } }
  - { image: Y.png                  , when: { black: 20, blue:  26, green:   0, red:   0 } }
  - { image: Z.png                  , when: { black: 20, blue:  27, green:   0, red:   0 } }
  - { image: Incognita.png          , when: { black: 40, blue: '*', green:   0, red:   0 } }
  - { image: 000.png                , when: { black: 30, blue:   0, green:   0, red:   0 } }
  - { image: 001.png                , when: { black: 30, blue:   1, green:   0, red:   0 } }
  - { image: 002.png                , when: { black: 30, blue:   2, green:   0, red:   0 } }
  - { image: 003.png                , when: { black: 30, blue:   3, green:   0, red:   0 } }
  - { image: 004.png                , when: { black: 30, blue:   4, green:   0, red:   0 } }
  - { image: 005.png                , when: { black: 30, blue:   5, green:   0, red:   0 } }
  - { image: 006.png                , when: { black: 30, blue:   6, green:   0, red:   0 } }
  - { image: 007.png                , when: { black: 30, blue:   7, green:   0, red:   0 } }
  - { image: 008.png                , when: { black: 30, blue:   8, green:   0, red:   0 } }
  - { image: 009.png                , when: { black: 30, blue:   9, green:   0, red:   0 } }
  - { image: 010.png                , when: { black: 30, blue:  10, green:   0, red:   0 } }
  - { image: 011.png                , when: { black: 30, blue:  11, green:   0, red:   0 } }
  - { image: 012.png                , when: { black: 30, blue:  12, green:   0, red:   0 } }
  - { image: 013.png                , when: { black: 30, blue:  13, green:   0, red:   0 } }
  - { image: 014.png                , when: { black: 30, blue:  14, green:   0, red:   0 } }
  - { image: 015.png                , when: { black: 30, blue:  15, green:   0, red:   0 } }
  - { image: 016.png                , when: { black: 30, blue:  16, green:   0, red:   0 } }
  - { image: 017.png                , when: { black: 30, blue:  17, green:   0, red:   0 } }
  - { image: 018.png                , when: { black: 30, blue:  18, green:   0, red:   0 } }
  - { image: 019.png                , when: { black: 30, blue:  19, green:   0, red:   0 } }
  - { image: 020.png                , when: { black: 30, blue:  20, green:   0, red:   0 } }
  - { image: 021.png                , when: { black: 30, blue:  21, green:   0, red:   0 } }
  - { image: 022.png                , when: { black: 30, blue:  22, green:   0, red:   0 } }
  - { image: 023.png                , when: { black: 30, blue:  23, green:   0, red:   0 } }
  - { image: 024.png                , when: { black: 30, blue:  24, green:   0, red:   0 } }
  - { image: 025.png                , when: { black: 30, blue:  25, green:   0, red:   0 } }
  - { image: 026.png                , when: { black: 30, blue:  26, green:   0, red:   0 } }
  - { image: 027.png                , when: { black: 30, blue:  27, green:   0, red:   0 } }
  - { image: 028.png                , when: { black: 30, blue:  28, green:   0, red:   0 } }
  - { image: 029.png                , when: { black: 30, blue:  29, green:   0, red:   0 } }
  - { image: 030.png                , when: { black: 30, blue:  30, green:   0, red:   0 } }
  - { image: 031.png                , when: { black: 30, blue:  31, green:   0, red:   0 } }
  - { image: 032.png                , when: { black: 30, blue:  32, green:   0, red:   0 } }
  - { image: 033.png                , when: { black: 30, blue:  33, green:   0, red:   0 } }
  - { image: 034.png                , when: { black: 30, blue:  34, green:   0, red:   0 } }
  - { image: 035.png                , when: { black: 30, blue:  35, green:   0, red:   0 } }
  - { image: 036.png                , when: { black: 30, blue:  36, green:   0, red:   0 } }
  - { image: 037.png                , when: { black: 30, blue:  37, green:   0, red:   0 } }
  - { image: 038.png                , when: { black: 30, blue:  38, green:   0, red:   0 } }
  - { image: 039.png                , when: { black: 30, blue:  39, green:   0, red:   0 } }
  - { image: 040.png                , when: { black: 30, blue:  40, green:   0, red:   0 } }
  - { image: 041.png                , when: { black: 30, blue:  41, green:   0, red:   0 } }
  - { image: 042.png                , when: { black: 30, blue:  42, green:   0, red:   0 } }
  - { image: 043.png                , when: { black: 30, blue:  43, green:   0, red:   0 } }
  - { image: 044.png                , when: { black: 30, blue:  44, green:   0, red:   0 } }
  - { image: 045.png                , when: { black: 30, blue:  45, green:   0, red:   0 } }
  - { image: 046.png                , when: { black: 30, blue:  46, green:   0, red:   0 } }
  - { image: 047.png                , when: { black: 30, blue:  47, green:   0, red:   0 } }
  - { image: 048.png                , when: { black: 30, blue:  48, green:   0, red:   0 } }
  - { image: 049.png                , when: { black: 30, blue:  49, green:   0, red:   0 } }
  - { image: 050.png                , when: { black: 30, blue:  50, green:   0, red:   0 } }
                                                                                       